name: "Sync docker-library"

on:
  push:
    branches:
      - master

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install deps
        run: sudo apt-get install -y libgpgme-dev libassuan-dev libdevmapper-dev libbtrfs-dev

      - name: Build
        run: make build

      - name: Checkout docker library
        uses: actions/checkout@v2
        with:
          repository: docker-library/official-images
          path: data

      - name: Sync
        env:
          GHCRI_REGISTRY: "ghcr.io"
          GHCRI_OWNER: "ghcri"
          GHCRI_USERNAME: ${{secrets.GHCRI_USERNAME}}
          GHCRI_PASSWORD: ${{secrets.GHCRI_PASSWORD}}
        run: sudo ./bin/ghcri data/library
